(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: CAN_Transceiver-PTH.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Thursday, 06 November 2025 at 14:35)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 1.0)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 170.0)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.7)

(Tools Offset: )
(Tool: 1 -> Offset Z: 0.0)

(DEPTH_PER_CUT: )
(Tool: 1 -> DeptPerCut: 0.55)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2.0)

(Z Toolchange: 35.0 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 0.5 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Preprocessor Excellon: default)

(X range:    2.7750 ...   22.5500  mm)
(Y range:    1.7350 ...   10.3550  mm)

(Spindle Speed: 11000 RPM)
G21
G90
G94

G01 F170.00

M5
G00 Z35.0000
T1
G00 X0.0000 Y0.0000                
M6
(MSG, Change to Tool Dia = 1.0000 ||| Total drills for tool T1 = 8)
M0
G00 Z35.0000

G01 F170.00
M03 S11000
G00 X3.2750 Y9.8550
G01 Z-0.5500
G01 Z0
G00 Z2.0000
G01 Z-1.1000
G01 Z0
G00 Z2.0000
G01 Z-1.6500
G01 Z0
G00 Z2.0000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X3.2750 Y7.3150
G01 Z-0.5500
G01 Z0
G00 Z2.0000
G01 Z-1.1000
G01 Z0
G00 Z2.0000
G01 Z-1.6500
G01 Z0
G00 Z2.0000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X3.2750 Y4.7750
G01 Z-0.5500
G01 Z0
G00 Z2.0000
G01 Z-1.1000
G01 Z0
G00 Z2.0000
G01 Z-1.6500
G01 Z0
G00 Z2.0000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X3.2750 Y2.2350
G01 Z-0.5500
G01 Z0
G00 Z2.0000
G01 Z-1.1000
G01 Z0
G00 Z2.0000
G01 Z-1.6500
G01 Z0
G00 Z2.0000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X19.4850 Y2.2750
G01 Z-0.5500
G01 Z0
G00 Z2.0000
G01 Z-1.1000
G01 Z0
G00 Z2.0000
G01 Z-1.6500
G01 Z0
G00 Z2.0000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X22.0250 Y2.2750
G01 Z-0.5500
G01 Z0
G00 Z2.0000
G01 Z-1.1000
G01 Z0
G00 Z2.0000
G01 Z-1.6500
G01 Z0
G00 Z2.0000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X22.0500 Y9.5250
G01 Z-0.5500
G01 Z0
G00 Z2.0000
G01 Z-1.1000
G01 Z0
G00 Z2.0000
G01 Z-1.6500
G01 Z0
G00 Z2.0000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X19.5100 Y9.5250
G01 Z-0.5500
G01 Z0
G00 Z2.0000
G01 Z-1.1000
G01 Z0
G00 Z2.0000
G01 Z-1.6500
G01 Z0
G00 Z2.0000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
M05
G00 Z0.50


